### PR TITLE
Fix logo button

### PR DESCRIPTION
**Pull request by nxllxvxxd**
Fixed logo click in items like Albums, Movies, TV shows, ect

### CODE REVIEW

**Review by tedhinklater — CHANGES_REQUESTED** [review]
Ah fantastic thanks, could you set it to this though

  position: fixed;
  top: 1em;
  left: 4.5em;
  width: calc(100vw / 1.65);
  height: 3em;

**Comment by nxllxvxxd** [comment]
see you know more about css than I so I just went with that method lmao

**Comment by tedhinklater** [comment]
I only discovered calc 2 days ago haha

**Comment by nxllxvxxd** [comment]
> I only discovered calc 2 days ago haha

you wouldn't happen to have like discord or something so I can dm you I have some ideas but I don't wanna put all that code in there if you don't want it lmao

**Comment by tedhinklater** [comment]
I don't have discord :/ maybe pastebin? something like this https://pastebin.com/TELwKZk8

You could make a new Paste and I can steal from it/add comments

**Pull request merged**
