### PR TITLE
merge

### PR DESCRIPTION
**Pull request by TrueBankai416**

### CODE REVIEW

**Comment by DevilsDesigns** [comment]
what did you change bangcock?

**Comment by DevilsDesigns** [comment]
aah readme was changed?

**Comment by TrueBankai416** [comment]
i didnt change anything, Any time i pull his changes it says that my repo is 1 more commit ahead of his (i dont understand this)

**Comment by DevilsDesigns** [comment]
Gotta love GitHub lolOn Jun 10, 2024 5:05 PM, TrueBankai416 ***@***.***> wrote:
i didnt change anything, Any time i pull his changes it says that my repo is 1 more commit ahead of his (i dont understand this)

**Comment by tedhinklater** [comment]
The only thing I can think, if you want to sync it, is just delete the repo and fork a new one?

**Review by DevilsDesigns — COMMENTED** [review]
Are you removing the spinner color?

**Comment by TrueBankai416** [comment]
> Are you removing the spinner color?

shouldnt be no, there were two copies of the same code for the spinner

**Comment by TrueBankai416** [comment]
image
@DevilsDesigns

**Comment by DevilsDesigns** [comment]
Aah good find!

**Pull request closed without merging**
