### PR TITLE
Update finality.css

### PR DESCRIPTION
**Pull request by DevilsDesigns**
added scrollbar matching for tv episodes
image

### CODE REVIEW

**Comment by tedhinklater** [comment]
I've really tried but I think the red scrollbar is too much red (make sure you enable Backdrops to remove that grey bar btw)

**Comment by TrueBankai416** [comment]
not sure if you guys noticed or have the same issue but everytime i close my close my browser, The user settings revert back to their original values.. so i have to enable backdrops everytime i open jellyfin in a browser

**Comment by tedhinklater** [comment]
Unfortunately it's not happening for me, on chrome/firefox/JMP and I tried 2 different computers..

**Comment by TrueBankai416** [comment]
strange, im using firefox. I also modified settings on other accounts and they also reverted back after a few hours

**Comment by tedhinklater** [comment]
> strange, im using firefox. I also modified settings on other accounts and they also reverted back after a few hours

I noticed Firefox was using @latest/finality.css from a few days ago, but @main loaded fine. Went to Manage Data and cleared 192.168.1.69 and @latest is showing the updated version. Might be a similar problem on your end @TrueBankai416 ?

**Comment by TrueBankai416** [comment]
The theme is remaining the same but If I change any user settings then they revert back, such as backdrops and theme music

Sent from Proton Mail Android

-------- Original Message --------

**Comment by TrueBankai416** [comment]
I'll clear cache just incase tho

Sent from Proton Mail Android

-------- Original Message --------

**Pull request merged**
