### PR TITLE
added pan and tilt to backdrop from BobHasNoSoul;

### PR DESCRIPTION
**Pull request by nxllxvxxd**

### CODE REVIEW

**Comment by tedhinklater** [comment]
unknown_2024 07 16-23 50_2

Jellyfin Media Player kinda freaks out with this and videos wont play

**Comment by nxllxvxxd** [comment]
that is very odd actually I really don't use the media player so I didn't even think to check

**Comment by nxllxvxxd** [comment]
actually very odd and could possibly be an AMD issue? I have an NVIDIA card and downloaded the desktop app to test and I have no problems with it inserted into custom CSS, hold up gotta upload gif to imgur cause it is 60 fps

**Comment by nxllxvxxd** [comment]
[Here](https://titl.tv/cloud/s/backdropgif), imgur isn't working I'll just share with my Nextcloud

**Comment by nxllxvxxd** [comment]
https://github.com/user-attachments/assets/13daeac1-c59d-4d0a-b6d2-26231eec5db4

**Comment by tedhinklater** [comment]
ok my bad I turned off Use OpenGL and it's got no problems now

**Pull request merged**
